version: '3.11'

services:
  # PostgreSQL Service
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: drb
      POSTGRES_PASSWORD: drbpw1@
      POSTGRES_DB: versus
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Elasticsearch Service
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=true
      - ELASTIC_PASSWORD=drbpw1@
    ports:
      - "9200:9200"
      - "9300:9300"

  # Redis Service
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  # Django Service
  django:
    build:
      context: .
    container_name: api
    volumes:
      - .:/usr/src/drb  # Adjusted to match Dockerfile WORKDIR
      - static_volume:/usr/src/drb/app/static  # Adjust for static files
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - elasticsearch
      - redis

  # Nginx Service
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/usr/src/drb/app/static  # Adjust for static files
    depends_on:
      - django

volumes:
  postgres_data:
  static_volume:

networks:
  default:
    name: drb_network
    external: true

